apiVersion: v1
kind: Secret
metadata:
  name: antiradicalshield-secrets
  namespace: antiradicalshield
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=  # base64 of "admin"
  POSTGRES_PASSWORD: MTIzNDU2  # base64 of "123456"
  POSTGRES_DB: YW50aXJhZGljYWxzaGllbGRfZGI=  # base64 of "antiradicalshield_db"
  SECRET_KEY: MTIzNDU2  # base64 of "123456"

